# Generated by Django 5.2.6 on 2025-11-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="carbon_footprint",
            field=models.CharField(
                blank=True,
                help_text="Carbon footprint information (e.g., kg CO2 saved)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="certifications",
            field=models.CharField(
                blank=True,
                help_text="e.g., GOTS, Fair Trade, OEKO-TEX, etc.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="conventional_impact",
            field=models.TextField(
                blank=True,
                help_text="Environmental impact of NOT using sustainable alternatives",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="environmental_benefits",
            field=models.TextField(
                blank=True, help_text="Benefits of using this sustainable product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturing_process",
            field=models.TextField(
                blank=True, help_text="Detailed process of how the product is made"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="raw_material_source",
            field=models.TextField(
                blank=True,
                help_text="Where the raw materials come from (origin, farms, suppliers)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="recyclability",
            field=models.CharField(
                blank=True,
                help_text="How the product can be recycled or disposed",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="transportation_method",
            field=models.TextField(
                blank=True,
                help_text="How raw materials are transported (carbon footprint, shipping methods)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="usage_advantages",
            field=models.TextField(
                blank=True, help_text="Why consumers should choose this product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="water_usage",
            field=models.CharField(
                blank=True, help_text="Water consumption in production", max_length=255
            ),
        ),
    ]
